Feature/39517
KushChauhanSS/express-server pull request #3
Opened 2021-08-28 16:48 UTC by KushChauhanSS

2021-08-30 10:34 UTC, adilsuccessive requested changes
hasPermission function is not working properly.
1. hasPermission('getUsers', 'head-trainer', 'write')       expected true but returns false
* head-trainer included in all section so, has permission for each of read,write and delete

2021-08-30 10:34 UTC, adilsuccessive commented on extras/utils/permissions.js
> +    const permdic = permissions[moduleName];
use valid and meaningful  variable names.

2021-08-31 07:36 UTC, KushChauhanSS reviewed
Done chnages

2021-08-31 07:56 UTC, adilsuccessive approved these changes

2021-08-31 07:57 UTC, merged